<?php

/**
 * Category
 * This class has been auto-generated by the Doctrine ORM Framework
 * @package    trade
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
    public function getFullName()
    {
        $result = [$this->getName()];

        $parent = $this->getParent();
        while ($parent->getId() !== null) {
            $result[] = $parent->getName();
            $parent = $parent->getParent();
        }

        return implode(' / ', array_reverse($result));
    }
}
