<?php

/**
 * CategoryTable
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }

    public static function getList()
    {
        /** @var Category[] $categories */
        $categories = Doctrine_Query::create()
            ->from('Category c')->execute();

        $result = ['' => ''];
        foreach ($categories as $category) {
            $result[$category->getId()] = $category->getFullName();
        }

        asort($result);

        return $result;
    }
}
