<?php

/**
 * GoodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GoodTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GoodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Good');
    }
}