<?php

/**
 * Good
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    trade
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Good extends BaseGood
{
  public function getTopCategoryId()
  {
    $category = $this->getCategory();
    $result = $category->getId();

    while ($category->getId() !== null) {
      $result = $category->getId();
      $category = $category->getParent();
    }

    return $result;
  }
}
