<?php

/**
 * OrderPositionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderPositionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderPositionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrderPosition');
    }
}