<?php

/**
 * Order
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    trade
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Order extends BaseOrder
{
  const STATES = [
    'created' => 'Создан',
    'in-progress' => 'В работе',
    'discarded' => 'Отклонён',
    'completed' => 'Выполнен',
  ];

  public function postInsert($event)
  {
    $key = ProjectConfiguration::MAILGUN_KEY;
    $domain = ProjectConfiguration::MAILGUN_DOMAIN;
    $from = ProjectConfiguration::MAILGUN_FROM;

    if (!$key || !$domain || !$from) {
      return;
    }

    $mg = new Mailgun\Mailgun($key);

    $mg->sendMessage($domain, [
      'from' => $from,
      'to' => 'anatoly.pashin@gmail.com, auction@olgerd.ru, customs@olgerd.ru',
      'subject' => 'Оформлен новый заказ',
      'text' => $this->generateEmailText(),
    ]);
  }

  public function getReadableState()
  {
    return self::STATES[$this->getState()];
  }

  protected function generateEmailText()
  {
    $_ = function($expr) {
      return $expr;
    };

    $positions = [];
    foreach ($this->getPositions() as $position) {
      $positions[] = "{$_($position->getAmount())} × {$_($position->getGood())}";
    }
    $positionsList = '  — ' . implode("\n  — ", $positions);

    return <<<EMAIL
На сайте был оформлен заказ от пользователя {$_($this->getCreator())}.

Состав заказа:
{$positionsList}


Вы можете просмотреть заказ на странице http://trade.olgerd.ru/backend.php/order/show?id={$_($this->getId())}
EMAIL;
  }
}
