# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow
    viewport:      width=device-width, initial-scale=1.0

  stylesheets:
    - bootstrap
    - lightbox.min.css
    - main.css?v=1

  javascripts:
    - "http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"
    - "https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js"
    - "https://cdnjs.cloudflare.com/ajax/libs/ngStorage/0.3.6/ngStorage.min.js"
    - bootstrap.min.js
    - lightbox.min.js
    - main.js?v=2

  has_layout:     true
  layout:         layout
