# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:host=localhost;port=5432;dbname=trade'
      username: postgres
      password: z123b15
      attributes:
        quote_identifier:  true
        use_native_enum:   true
        use_dql_callbacks: true
