<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('image', 'image_good_id_good_id', array(
             'name' => 'image_good_id_good_id',
             'local' => 'good_id',
             'foreign' => 'id',
             'foreignTable' => 'good',
             ));
        $this->addIndex('image', 'image_good_id', array(
             'fields' =>
             array(
              0 => 'good_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('image', 'image_good_id_good_id');
        $this->removeIndex('image', 'image_good_id', array(
             'fields' =>
             array(
              0 => 'good_id',
             ),
             ));
    }
}
