<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('good', 'introduction', 'clob', '', array(
             'notnull' => '1',
             'default' => '',
             ));
        $this->addColumn('good_version', 'introduction', 'clob', '', array(
             'notnull' => '1',
             'default' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('good', 'introduction');
        $this->removeColumn('good_version', 'introduction');
    }
}
