<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('category', array(
             'id' =>
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' =>
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'image' =>
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'created_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'updated_by' =>
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'deleted_at' =>
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
             ),
             ));
        $this->addColumn('good', 'category_id', 'integer', '8', array(
             ));
        $this->addColumn('good_version', 'category_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('category');
        $this->removeColumn('good', 'category_id');
        $this->removeColumn('good_version', 'category_id');
    }
}
