<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('order', 'order_created_by_sf_guard_user_id', array(
             'name' => 'order_created_by_sf_guard_user_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('order', 'order_updated_by_sf_guard_user_id', array(
             'name' => 'order_updated_by_sf_guard_user_id',
             'local' => 'updated_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('order_position', 'order_position_good_id_good_id', array(
             'name' => 'order_position_good_id_good_id',
             'local' => 'good_id',
             'foreign' => 'id',
             'foreignTable' => 'good',
             ));
        $this->createForeignKey('order_position', 'order_position_order_id_order_id', array(
             'name' => 'order_position_order_id_order_id',
             'local' => 'order_id',
             'foreign' => 'id',
             'foreignTable' => 'order',
             ));
        $this->createForeignKey('order_position', 'order_position_created_by_sf_guard_user_id', array(
             'name' => 'order_position_created_by_sf_guard_user_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('order_position', 'order_position_updated_by_sf_guard_user_id', array(
             'name' => 'order_position_updated_by_sf_guard_user_id',
             'local' => 'updated_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('order', 'order_created_by', array(
             'fields' =>
             array(
              0 => 'created_by',
             ),
             ));
        $this->addIndex('order', 'order_updated_by', array(
             'fields' =>
             array(
              0 => 'updated_by',
             ),
             ));
        $this->addIndex('order_position', 'order_position_good_id', array(
             'fields' =>
             array(
              0 => 'good_id',
             ),
             ));
        $this->addIndex('order_position', 'order_position_order_id', array(
             'fields' =>
             array(
              0 => 'order_id',
             ),
             ));
        $this->addIndex('order_position', 'order_position_created_by', array(
             'fields' =>
             array(
              0 => 'created_by',
             ),
             ));
        $this->addIndex('order_position', 'order_position_updated_by', array(
             'fields' =>
             array(
              0 => 'updated_by',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('order', 'order_created_by_sf_guard_user_id');
        $this->dropForeignKey('order', 'order_updated_by_sf_guard_user_id');
        $this->dropForeignKey('order_position', 'order_position_good_id_good_id');
        $this->dropForeignKey('order_position', 'order_position_order_id_order_id');
        $this->dropForeignKey('order_position', 'order_position_created_by_sf_guard_user_id');
        $this->dropForeignKey('order_position', 'order_position_updated_by_sf_guard_user_id');
        $this->removeIndex('order', 'order_created_by', array(
             'fields' =>
             array(
              0 => 'created_by',
             ),
             ));
        $this->removeIndex('order', 'order_updated_by', array(
             'fields' =>
             array(
              0 => 'updated_by',
             ),
             ));
        $this->removeIndex('order_position', 'order_position_good_id', array(
             'fields' =>
             array(
              0 => 'good_id',
             ),
             ));
        $this->removeIndex('order_position', 'order_position_order_id', array(
             'fields' =>
             array(
              0 => 'order_id',
             ),
             ));
        $this->removeIndex('order_position', 'order_position_created_by', array(
             'fields' =>
             array(
              0 => 'created_by',
             ),
             ));
        $this->removeIndex('order_position', 'order_position_updated_by', array(
             'fields' =>
             array(
              0 => 'updated_by',
             ),
             ));
    }
}
