<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('order', 'state', 'enum', '', array(
             'values' =>
             array(
              0 => 'created',
              1 => 'in-progress',
              2 => 'discarded',
              3 => 'completed',
             ),
             'default' => 'created',
             ));
    }

    public function down()
    {
        $this->removeColumn('order', 'state');
    }
}
