Good:
  actAs:
    - Signable
    - Timestampable
    - SoftDelete
    - Versionable
  columns:
    name:
      type: string(255)
      notnull: true
    dimension_id:
      type: integer
      notnull: true
    price:
      type: decimal
      scale: 2
      notnull: true
    amount:
      type: integer
      notnull: true
    description:
      type: clob
      notnull: true
  relations:
    Dimension:
      local: dimension_id
      foreign: id
      foreignAlias: Goods

Dimension:
  actAs:
    - Signable
    - Timestampable
    - SoftDelete
    - Versionable
  columns:
    name:
      type: string(255)
      notnull: true
