Good:
  actAs:
    - Signable
    - Timestampable
    - SoftDelete
    - Versionable
  columns:
    name:
      type: string(255)
      notnull: true
    category_id:
      type: integer
    dimension_id:
      type: integer
      notnull: true
    price:
      type: decimal
      scale: 2
      notnull: true
    amount:
      type: integer
      notnull: true
    introduction:
      type: clob
      notnull: true
    description:
      type: clob
      notnull: true
  relations:
    Category:
      local: category_id
      foreign: id
      foreignAlias: Goods
    Dimension:
      local: dimension_id
      foreign: id
      foreignAlias: Goods
    Images:
      class: Image
      local: id
      foreign: good_id
      type: many
      foreignType: one

Dimension:
  actAs:
    - Signable
    - Timestampable
    - SoftDelete
    - Versionable
  columns:
    name:
      type: string(255)
      notnull: true

Image:
  actAs:
    - Signable
    - Timestampable
    - SoftDelete
  columns:
    good_id:
      type: integer
      notnull: true
    name:
      type: string(255)
      notnull: true
    is_default:
      type: boolean
      notnull: true
      default: false

Category:
  actAs:
    - Signable
    - Timestampable
    - SoftDelete
  columns:
    name:
      type: string(255)
      notnull: true
    parent_id:
      type: integer
    image:
      type: string(255)
  relations:
    Parent:
      class: Category
      local: parent_id
      foreign: id
      foreignAlias: Children
